version : "3.5"
services:
  mysql:
    image: mysql:8
    container_name: mysql 

    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=tecnobyte_bd
    volumes:
      - "./mysql:/var/lib/mysql"
  api:
    depends_on:  
      - mysql
    image: ggmartinez/laravel:php-82
    container_name: autentic 
    ports:
      - "8000:8000"
    volumes:
      - "./:/app"